version: 0.2

phases:
  pre_build:
    commands:
    - npm install --no-progress --silent
  build:
    commands:
    - npm run-script lint
    - mkdir -p target/stg
    - mkdir target/prod
    - serverless package --package target/stg --stage stg -v -r us-east-1
    - serverless package --package target/prod --stage prod -v -r us-east-1

artifacts:
  files:
  - target/**/*
  - serverless.yml
  - deploy.sh